services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: diwo
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: places
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U diwo -d places"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: diwo
      DB_PASSWORD: secret
      DB_NAME: places
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/places/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  pgdata: