version: '3.8'

services:
  db:
    image: postgres:15
    container_name: diwo-db
    environment:
      POSTGRES_USER: diwo
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: places
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U diwo -d places"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: diwo-app
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: diwo
      DB_PASSWORD: secret
      DB_NAME: places
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: